module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests/e2e'],
  testMatch: ['**/*.e2e.test.ts'],
  moduleNameMapper: {
    '^@deltecho/membrane-transport$': '<rootDir>/packages/membrane-transport/src',
    '^@deltecho/gesture-glyph$': '<rootDir>/packages/gesture-glyph/src',
    '^@deltecho/cognitive$': '<rootDir>/packages/cognitive/index.ts',
    '^@deltecho/reasoning$': '<rootDir>/packages/reasoning/index.ts',
    '^@deltecho/shared$': '<rootDir>/packages/shared/index.ts',
    '^@deltecho/sys6-triality$': '<rootDir>/packages/sys6-triality/src/index.ts',
    '^deep-tree-echo-core$': '<rootDir>/deep-tree-echo-core/src/index.ts',
    '^dove9$': '<rootDir>/dove9/src/index.ts',
  },
  collectCoverageFrom: [
    'packages/*/src/**/*.ts',
    'packages/*/*.ts',
    'deep-tree-echo-core/src/**/*.ts',
    'dove9/src/**/*.ts',
    '!packages/*/src/**/*.d.ts',
    '!**/__tests__/**',
    '!**/*.test.ts',
    '!**/*.spec.ts',
    '!**/node_modules/**',
    '!**/dist/**',
  },
  coverageDirectory: 'coverage-e2e',
  coverageReporters: ['text', 'lcov', 'html'],
  verbose: true,
  testTimeout: 30000,
};
