/**
 * @fileoverview Mathar Flip Transform
 *
 * Implements the structural relationship between free trees (clusters)
 * and rooted trees (terms) via the flip transform, where integer
 * partitions form the rows of the transform matrix.
 *
 * Key sequences:
 *   A000055 (free/unrooted trees):  1, 1, 1, 1, 2, 3,  6,  11,  23, ...
 *   A000081 (rooted trees):         1, 1, 2, 4, 9, 20, 48, 115, 286, ...
 *
 * For System N (with N+1 nodes):
 *   Sys1: 1 cluster  → 1 term
 *   Sys2: 1 cluster  → 2 terms
 *   Sys3: 2 clusters → 4 terms
 *   Sys4: 3 clusters → 9 terms
 *   Sys5: 6 clusters → 20 terms
 *   Sys6: 11 clusters → 48 terms
 *
 * The flip transform maps each free tree to its set of rooted
 * orientations. The number of rooted orientations of a free tree
 * equals the number of distinct rootings, which depends on the
 * tree's automorphism group. Integer partitions of N+1 classify
 * the symmetry types and form the transform matrix rows.
 *
 * References:
 *   Mathar, R.J. "Topologies of non-intersecting circles on a sphere"
 *   Otter, R. "The number of trees" (1948)
 *   Harary, F. & Palmer, E. "Graphical Enumeration" (1973)
 */

import { type SystemLevel, A000081 } from './types.js';

// ============================================================
// OEIS A000055: Number of unrooted (free) trees on n nodes
// ============================================================

/**
 * A000055: Number of unrooted trees on n nodes
 * a(0)=1, a(1)=1, a(2)=1, a(3)=1, a(4)=2, a(5)=3, a(6)=6, a(7)=11, a(8)=23
 *
 * Related to A000081 by Otter's formula:
 *   a(n) = A000081(n) - sum_{j=1..n/2} A000081(j)*A000081(n-j)
 *          + [n even] * A000081(n/2)*(A000081(n/2)+1)/2
 */
export const A000055: readonly number[] = [1, 1, 1, 1, 2, 3, 6, 11, 23, 47] as const;

// ============================================================
// Integer Partitions
// ============================================================

/**
 * An integer partition of n is a non-increasing sequence of positive
 * integers that sum to n. These classify the symmetry types of trees.
 */
export interface IntegerPartition {
  /** The parts, in non-increasing order */
  parts: number[];
  /** The integer being partitioned */
  n: number;
  /** Number of parts */
  length: number;
  /** Conjugacy class label */
  label: string;
}

/**
 * Generate all integer partitions of n
 * Returns partitions in reverse lexicographic order
 */
export function integerPartitions(n: number): IntegerPartition[] {
  const result: IntegerPartition[] = [];

  function generate(remaining: number, maxPart: number, current: number[]): void {
    if (remaining === 0) {
      const parts = [...current];
      result.push({
        parts,
        n,
        length: parts.length,
        label: parts.join('+'),
      });
      return;
    }

    for (let part = Math.min(remaining, maxPart); part >= 1; part--) {
      current.push(part);
      generate(remaining - part, part, current);
      current.pop();
    }
  }

  generate(n, n, []);
  return result;
}

/**
 * Count the number of integer partitions of n
 * (OEIS A000041: 1, 1, 2, 3, 5, 7, 11, 15, 22, 30, 42, ...)
 */
export function partitionCount(n: number): number {
  return integerPartitions(n).length;
}

// ============================================================
// Cluster (Free Tree) Definition
// ============================================================

/**
 * A cluster is a free (unrooted) tree — an equivalence class of
 * rooted trees under the flip transform. Each cluster generates
 * one or more rooted trees depending on its symmetry.
 */
export interface Cluster {
  /** Cluster index (1-based) */
  index: number;
  /** Number of nodes */
  nodes: number;
  /** Number of rooted orientations this cluster generates */
  rootedCount: number;
  /** The symmetry partition that characterizes this cluster */
  symmetryPartition: IntegerPartition;
  /** Description */
  description: string;
  /** Indices of terms (rooted trees) generated by this cluster */
  termIndices: number[];
}

// ============================================================
// Flip Transform Matrix
// ============================================================

/**
 * A row of the flip transform matrix.
 * Each row corresponds to an integer partition of n+1 (the node count).
 * The entries indicate how many rooted trees of each symmetry type
 * are generated from free trees of that partition type.
 */
export interface FlipTransformRow {
  /** The partition defining this row */
  partition: IntegerPartition;
  /** Number of free trees with this symmetry type */
  freeTrees: number;
  /** Number of rooted trees generated per free tree */
  rootingsPerTree: number;
  /** Total rooted trees from this row */
  totalRooted: number;
}

/**
 * The complete flip transform for a system level
 */
export interface FlipTransform {
  /** System level */
  level: SystemLevel;
  /** Number of nodes (N+1) */
  nodes: number;
  /** Number of clusters (free trees) = A000055[N+1] */
  clusterCount: number;
  /** Number of terms (rooted trees) = A000081[N+1] */
  termCount: number;
  /** The clusters */
  clusters: Cluster[];
  /** The transform matrix rows */
  matrix: FlipTransformRow[];
  /** Integer partitions of the node count */
  partitions: IntegerPartition[];
  /** Verification: sum of totalRooted across matrix rows */
  verifiedTermCount: number;
}

// ============================================================
// System-specific Cluster Definitions
// ============================================================

/**
 * Build clusters for System N.
 *
 * The cluster structure is derived from the free trees on N+1 nodes.
 * Each free tree can be rooted at different nodes, generating
 * distinct rooted trees. The number of distinct rootings depends
 * on the automorphism group of the free tree.
 */
function buildClusters(level: SystemLevel): Cluster[] {
  const nodes = level + 1;

  switch (level) {
    case 1:
      // 2 nodes: 1 free tree (edge), 1 rooting
      return [{
        index: 1,
        nodes: 2,
        rootedCount: 1,
        symmetryPartition: { parts: [2], n: 2, length: 1, label: '2' },
        description: 'The single edge — symmetric, 1 rooting',
        termIndices: [1],
      }];

    case 2:
      // 3 nodes: 1 free tree (path P₃), 2 rootings
      return [{
        index: 1,
        nodes: 3,
        rootedCount: 2,
        symmetryPartition: { parts: [2, 1], n: 3, length: 2, label: '2+1' },
        description: 'Path P₃ — root at centre (chain) or end (branch)',
        termIndices: [1, 2],
      }];

    case 3:
      // 4 nodes: 2 free trees, 4 rootings total
      return [
        {
          index: 1,
          nodes: 4,
          rootedCount: 2,
          symmetryPartition: { parts: [3, 1], n: 4, length: 2, label: '3+1' },
          description: 'Path P₄ — root at interior (2 distinct) or end (same by symmetry)',
          termIndices: [1, 2],
        },
        {
          index: 2,
          nodes: 4,
          rootedCount: 2,
          symmetryPartition: { parts: [2, 1, 1], n: 4, length: 3, label: '2+1+1' },
          description: 'Star K₁,₃ — root at centre (star) or leaf (chain-2 + leaf)',
          termIndices: [3, 4],
        },
      ];

    case 4:
      // 5 nodes: 3 free trees, 9 rootings total
      return [
        {
          index: 1,
          nodes: 5,
          rootedCount: 3,
          symmetryPartition: { parts: [4, 1], n: 5, length: 2, label: '4+1' },
          description: 'Path P₅ — 3 distinct rootings (end, near-end, centre)',
          termIndices: [1, 2, 3],
        },
        {
          index: 2,
          nodes: 5,
          rootedCount: 4,
          symmetryPartition: { parts: [2, 2, 1], n: 5, length: 3, label: '2+2+1' },
          description: 'T-tree (caterpillar) — 4 distinct rootings',
          termIndices: [4, 5, 6, 7],
        },
        {
          index: 3,
          nodes: 5,
          rootedCount: 2,
          symmetryPartition: { parts: [2, 1, 1, 1], n: 5, length: 4, label: '2+1+1+1' },
          description: 'Star K₁,₄ — root at centre (star-4) or leaf',
          termIndices: [8, 9],
        },
      ];

    case 5:
      // 6 nodes: 6 free trees, 20 rootings total
      return [
        {
          index: 1,
          nodes: 6,
          rootedCount: 3,
          symmetryPartition: { parts: [5, 1], n: 6, length: 2, label: '5+1' },
          description: 'Path P₆ — 3 distinct rootings',
          termIndices: [1, 2, 3],
        },
        {
          index: 2,
          nodes: 6,
          rootedCount: 5,
          symmetryPartition: { parts: [3, 2, 1], n: 6, length: 3, label: '3+2+1' },
          description: 'Caterpillar with tail — 5 distinct rootings',
          termIndices: [4, 5, 6, 7, 8],
        },
        {
          index: 3,
          nodes: 6,
          rootedCount: 3,
          symmetryPartition: { parts: [3, 1, 1, 1], n: 6, length: 4, label: '3+1+1+1' },
          description: 'Spider (3-star with extension) — 3 distinct rootings',
          termIndices: [9, 10, 11],
        },
        {
          index: 4,
          nodes: 6,
          rootedCount: 4,
          symmetryPartition: { parts: [2, 2, 2], n: 6, length: 3, label: '2+2+2' },
          description: 'Double-T tree — 4 distinct rootings',
          termIndices: [12, 13, 14, 15],
        },
        {
          index: 5,
          nodes: 6,
          rootedCount: 3,
          symmetryPartition: { parts: [2, 2, 1, 1], n: 6, length: 4, label: '2+2+1+1' },
          description: 'Y-tree with extension — 3 distinct rootings',
          termIndices: [16, 17, 18],
        },
        {
          index: 6,
          nodes: 6,
          rootedCount: 2,
          symmetryPartition: { parts: [2, 1, 1, 1, 1], n: 6, length: 5, label: '2+1+1+1+1' },
          description: 'Star K₁,₅ — root at centre (star-5) or leaf',
          termIndices: [19, 20],
        },
      ];

    case 6:
      // 7 nodes: 11 free trees, 48 rootings total
      return [
        {
          index: 1, nodes: 7, rootedCount: 4,
          symmetryPartition: { parts: [6, 1], n: 7, length: 2, label: '6+1' },
          description: 'Path P₇ — 4 distinct rootings',
          termIndices: [1, 2, 3, 4],
        },
        {
          index: 2, nodes: 7, rootedCount: 6,
          symmetryPartition: { parts: [4, 2, 1], n: 7, length: 3, label: '4+2+1' },
          description: 'Long caterpillar — 6 distinct rootings',
          termIndices: [5, 6, 7, 8, 9, 10],
        },
        {
          index: 3, nodes: 7, rootedCount: 4,
          symmetryPartition: { parts: [4, 1, 1, 1], n: 7, length: 4, label: '4+1+1+1' },
          description: 'Extended spider — 4 distinct rootings',
          termIndices: [11, 12, 13, 14],
        },
        {
          index: 4, nodes: 7, rootedCount: 6,
          symmetryPartition: { parts: [3, 3, 1], n: 7, length: 3, label: '3+3+1' },
          description: 'Symmetric double-arm — 6 distinct rootings',
          termIndices: [15, 16, 17, 18, 19, 20],
        },
        {
          index: 5, nodes: 7, rootedCount: 5,
          symmetryPartition: { parts: [3, 2, 2], n: 7, length: 3, label: '3+2+2' },
          description: 'Balanced caterpillar — 5 distinct rootings',
          termIndices: [21, 22, 23, 24, 25],
        },
        {
          index: 6, nodes: 7, rootedCount: 4,
          symmetryPartition: { parts: [3, 2, 1, 1], n: 7, length: 4, label: '3+2+1+1' },
          description: 'Asymmetric T-branch — 4 distinct rootings',
          termIndices: [26, 27, 28, 29],
        },
        {
          index: 7, nodes: 7, rootedCount: 3,
          symmetryPartition: { parts: [3, 1, 1, 1, 1], n: 7, length: 5, label: '3+1+1+1+1' },
          description: 'Extended star — 3 distinct rootings',
          termIndices: [30, 31, 32],
        },
        {
          index: 8, nodes: 7, rootedCount: 5,
          symmetryPartition: { parts: [2, 2, 2, 1], n: 7, length: 4, label: '2+2+2+1' },
          description: 'Triple-T tree — 5 distinct rootings',
          termIndices: [33, 34, 35, 36, 37],
        },
        {
          index: 9, nodes: 7, rootedCount: 4,
          symmetryPartition: { parts: [2, 2, 1, 1, 1], n: 7, length: 5, label: '2+2+1+1+1' },
          description: 'Wide Y-tree — 4 distinct rootings',
          termIndices: [38, 39, 40, 41],
        },
        {
          index: 10, nodes: 7, rootedCount: 5,
          symmetryPartition: { parts: [2, 1, 1, 1, 1, 1], n: 7, length: 6, label: '2+1+1+1+1+1' },
          description: 'Near-star — 5 distinct rootings',
          termIndices: [42, 43, 44, 45, 46],
        },
        {
          index: 11, nodes: 7, rootedCount: 2,
          symmetryPartition: { parts: [1, 1, 1, 1, 1, 1, 1], n: 7, length: 7, label: '1+1+1+1+1+1+1' },
          description: 'Star K₁,₆ — root at centre (star-6) or leaf',
          termIndices: [47, 48],
        },
      ];

    default:
      return [];
  }
}

// ============================================================
// Flip Transform Builder
// ============================================================

/**
 * Build the complete flip transform for a system level.
 *
 * The transform maps:
 *   A000055[N+1] clusters (free trees) → A000081[N+1] terms (rooted trees)
 *
 * The integer partitions of N+1 form the rows of the transform matrix,
 * classifying the symmetry types of the free trees.
 */
export function buildFlipTransform(level: SystemLevel): FlipTransform {
  const nodes = level + 1;
  const clusters = buildClusters(level);
  const partitions = integerPartitions(nodes);

  // Build transform matrix rows from clusters
  const matrix: FlipTransformRow[] = clusters.map(cluster => ({
    partition: cluster.symmetryPartition,
    freeTrees: 1,
    rootingsPerTree: cluster.rootedCount,
    totalRooted: cluster.rootedCount,
  }));

  const verifiedTermCount = clusters.reduce((sum, c) => sum + c.rootedCount, 0);

  return {
    level,
    nodes,
    clusterCount: clusters.length,
    termCount: A000081[nodes],
    clusters,
    matrix,
    partitions,
    verifiedTermCount,
  };
}

/**
 * Verify the flip transform for a system level:
 *   sum(cluster.rootedCount) === A000081[N+1]
 *   clusters.length === A000055[N+1]
 */
export function verifyFlipTransform(level: SystemLevel): {
  valid: boolean;
  details: {
    level: SystemLevel;
    nodes: number;
    expectedClusters: number;
    actualClusters: number;
    expectedTerms: number;
    actualTerms: number;
    clustersValid: boolean;
    termsValid: boolean;
  };
} {
  const transform = buildFlipTransform(level);
  const nodes = level + 1;

  const expectedClusters = A000055[nodes];
  const expectedTerms = A000081[nodes];

  const clustersValid = transform.clusterCount === expectedClusters;
  const termsValid = transform.verifiedTermCount === expectedTerms;

  return {
    valid: clustersValid && termsValid,
    details: {
      level,
      nodes,
      expectedClusters,
      actualClusters: transform.clusterCount,
      expectedTerms,
      actualTerms: transform.verifiedTermCount,
      clustersValid,
      termsValid,
    },
  };
}

/**
 * Verify the flip transform for all 6 system levels
 */
export function verifyAllFlipTransforms(): {
  valid: boolean;
  results: Array<ReturnType<typeof verifyFlipTransform>['details']>;
} {
  const results: Array<ReturnType<typeof verifyFlipTransform>['details']> = [];
  let allValid = true;

  for (let n = 1; n <= 6; n++) {
    const result = verifyFlipTransform(n as SystemLevel);
    results.push(result.details);
    if (!result.valid) allValid = false;
  }

  return { valid: allValid, results };
}

/**
 * Get the cluster that generates a specific term (rooted tree)
 * Returns the cluster index (1-based) or -1 if not found
 */
export function getClusterForTerm(level: SystemLevel, termIndex: number): number {
  const clusters = buildClusters(level);
  for (const cluster of clusters) {
    if (cluster.termIndices.includes(termIndex)) {
      return cluster.index;
    }
  }
  return -1;
}
